# Basic Information 
title: Yueru Jia
position: Master Student
affiliation: School of Computer Science, Peking University
# affiliation_link: https://www.illinois.edu/
# affiliation_logo: ./assets/img/illinois.svg
email: jiayueru (at) stu.pku.edu

# Search Engine Optimization (SEO)
keywords: jiayueru, Yueru Jia, yueru jia, yuerujia
canonical: https://jiayueru.github.io/
description: Yueru Jia is a master student at Peking University. Her research lies in robotics and generative AI.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.cz/citations?hl=zh-CN&user=ysU_eckAAAAJ
github_link: https://github.com/yaoyao-liu/
# linkedin: https://github.com/jiayueru
twitter: https://x.com/JiaYueru68071

# Images 
avatar: ./assets/img/me.jpg
favicon: ./assets/img/pku.png
favicon_dark: ./assets/img/pku.png
# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
